In [1]:
import yaml
import pandas as pd
import numpy as np
import torch
print('Import success! \nReady to go!')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

with open('config/params.yaml', 'r') as file:
    config = yaml.safe_load(file)
params_extract = config['extract']
params_learn = config['learn']
params_paths = config['paths']

params_paths
# params_extract


Import success! 
Ready to go!
Using device: cpu


{'pretrained': './pretrained_model.pth',
 'checkpoint': './checkpoint.pth',
 'dataset_path': '../fsd18kdataset',
 'train_csv': '../fsd18kdataset/FSDnoisy18k.meta/train.csv',
 'test_csv': '../fsd18kdataset/FSDnoisy18k.meta/test.csv',
 'test_audio_input': '../fsd18kdataset/FSDnoisy18k.audio_test',
 'train_audio_input': '../fsd18kdataset/FSDnoisy18k.audio_train',
 'train_feature_extracted': '../features/audio_train_varup2',
 'test_feature_extracted': '../features/audio_test_varup2'}

In [2]:
# 1. 加载 Train csv 数据
train_csv = pd.read_csv(params_paths['train_csv'])
train_csv.head()


# 2. 分离干净/噪声数据
clean_idx = train_csv[train_csv['manually_verified'] == 1].index  # 干净数据索引
noisy_idx = train_csv[train_csv['manually_verified'] == 0].index  # 噪声数据索引

# 3. 提取噪声样本ID (从文件名提取数字部分)
noisy_ids = [int(fname.split('.')[0]) for fname in train_csv.loc[noisy_idx, 'fname']]

# 4. 创建标签映射
labels = sorted(train_csv['label'].unique())    # 所有标签（按字母顺序）（唯一）
label_to_int = {label: i for i, label in enumerate(labels)} # 标签到数字的映射
int_to_label = {i: label for label, i in label_to_int.items()}

# 5. 创建文件路径到标签的映射
file_to_label = {
    f"{params_paths['train_audio_input']}/{row.fname}": row.label 
    for _, row in train_csv.iterrows()
}

# 6. 创建文件路径到数字标签的映射
file_to_int = {
    path: label_to_int[label] 
    for path, label in file_to_label.items()
}

# 打印检查
print(f"干净数据数量: {len(clean_idx)}")
print(f"噪声数据数量: {len(noisy_idx)}")
print(f"标签映射示例: {label_to_int}")
print(f"前5个文件标签: {list(file_to_label.items())[:5]}")
file_to_int
file_to_label
label_to_int

干净数据数量: 1772
噪声数据数量: 15813
标签映射示例: {'Acoustic_guitar': 0, 'Bass_guitar': 1, 'Clapping': 2, 'Coin_(dropping)': 3, 'Crash_cymbal': 4, 'Dishes_and_pots_and_pans': 5, 'Engine': 6, 'Fart': 7, 'Fire': 8, 'Fireworks': 9, 'Glass': 10, 'Hi-hat': 11, 'Piano': 12, 'Rain': 13, 'Slam': 14, 'Squeak': 15, 'Tearing': 16, 'Walk_or_footsteps': 17, 'Wind': 18, 'Writing': 19}
前5个文件标签: [('../fsd18kdataset/FSDnoisy18k.audio_train/94322.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_train/85602.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_train/240356.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_train/371015.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_train/264589.wav', 'Walk_or_footsteps')]


{'Acoustic_guitar': 0,
 'Bass_guitar': 1,
 'Clapping': 2,
 'Coin_(dropping)': 3,
 'Crash_cymbal': 4,
 'Dishes_and_pots_and_pans': 5,
 'Engine': 6,
 'Fart': 7,
 'Fire': 8,
 'Fireworks': 9,
 'Glass': 10,
 'Hi-hat': 11,
 'Piano': 12,
 'Rain': 13,
 'Slam': 14,
 'Squeak': 15,
 'Tearing': 16,
 'Walk_or_footsteps': 17,
 'Wind': 18,
 'Writing': 19}

In [3]:
# 1. 加载 test csv 数据
test_csv = pd.read_csv(params_paths['test_csv'])
test_csv.head()

# 4. 创建标签映射
test_labels = sorted(test_csv['label'].unique())    # 所有标签（按字母顺序）（唯一）
test_label_to_int = {label: i for i, label in enumerate(test_labels)} # 标签到数字的映射
test_int_to_label = {i: label for label, i in test_label_to_int.items()}

# 5. 创建文件路径到标签的映射
test_file_to_label = {
    f"{params_paths['test_audio_input']}/{row.fname}": row.label 
    for _, row in test_csv.iterrows()
}

# 6. 创建文件路径到数字标签的映射
test_file_to_int = {
    path: test_label_to_int[label] 
    for path, label in test_file_to_label.items()
}
print(f"标签映射示例: {test_label_to_int}")
print(f"前5个文件标签: {list(test_file_to_label.items())[:5]}")

test_file_to_int

标签映射示例: {'Acoustic_guitar': 0, 'Bass_guitar': 1, 'Clapping': 2, 'Coin_(dropping)': 3, 'Crash_cymbal': 4, 'Dishes_and_pots_and_pans': 5, 'Engine': 6, 'Fart': 7, 'Fire': 8, 'Fireworks': 9, 'Glass': 10, 'Hi-hat': 11, 'Piano': 12, 'Rain': 13, 'Slam': 14, 'Squeak': 15, 'Tearing': 16, 'Walk_or_footsteps': 17, 'Wind': 18, 'Writing': 19}
前5个文件标签: [('../fsd18kdataset/FSDnoisy18k.audio_test/274679.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_test/365220.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_test/233458.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_test/370931.wav', 'Walk_or_footsteps'), ('../fsd18kdataset/FSDnoisy18k.audio_test/137172.wav', 'Walk_or_footsteps')]


{'../fsd18kdataset/FSDnoisy18k.audio_test/274679.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/365220.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/233458.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/370931.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/137172.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/344769.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/30934.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/186037.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/424600.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/119086.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/352360.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/152901.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/345685.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/419931.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/251788.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/431893.wav': 17,
 '../fsd18kdataset/FSDnoisy18k.audio_test/55064.wav': 17,

In [4]:
# Mel 频谱图的生成
import os
import numpy as np
from tqdm import tqdm
from feat_ext import load_audio_file, modify_file_variable_length, get_mel_spectrogram
import utils



def extract_features(input_dir, output_dir, force_reprocess=False):
    """
    使用原作者的工具函数提取特征
    """
    os.makedirs(output_dir, exist_ok=True)
    
    audio_files = [f for f in os.listdir(input_dir) if f.endswith('.wav')]
    # print(audio_files)
    
    # 检查 .data 结尾的文件，存在则替换成 .wav，检查其他还未处理的数据
    if not force_reprocess:
        existing_features = {f.replace('_mel.data', '.wav') for f in os.listdir(output_dir) if f.endswith('_mel.data')}
        files_to_process = [f for f in audio_files if f not in existing_features]
    else:
        files_to_process = audio_files

    if not files_to_process:
        print("所有特征文件已存在，无需处理")
        return
    
    pbar = tqdm(files_to_process, desc="Extracting features")
    
    for fname in pbar:
        try:
            audio_path = os.path.join(input_dir, fname)
            # print(audio_path)
            # 使用原作者的音频加载函数
            y = load_audio_file(audio_path, 
                              input_fixed_length=params_extract['audio_len_s'],
                              params_extract=params_extract)
            # print(audio_path)
            # print(f"Loaded audio shape: {y.shape}")  # 打印加载的音频形状

            # 使用原作者的长度调整函数
            y = modify_file_variable_length(y,
                                         input_fixed_length=params_extract['audio_len_s'],
                                         params_extract=params_extract)
            # print(audio_path)
            # 使用原作者的梅尔频谱计算函数
            mel_spec = get_mel_spectrogram(y, params_extract)
            # print(audio_path)
            # print(f"Mel spectrogram shape: {mel_spec.shape}")  # 打印梅尔频谱图的形状
            # print()

            output_path = os.path.join(output_dir, fname.replace('.wav', '.data'))
            utils.save_tensor(var=mel_spec, 
                            out_path=output_path, 
                            suffix='_mel')
            # print(audio_path)


            # 保存标签 - 使用file_to_int获取正确的标签索引
            if 'test' in audio_path:
                # print(audio_path, 'test in audio')
                label_idx = test_file_to_int[audio_path]
            else:
                label_idx = file_to_int[audio_path]  # 从映射字典获取标签索引
                
            # print(audio_path)
            utils.save_tensor(var=np.array([label_idx], dtype=float),
                            out_path=output_path,
                            suffix='_label')
            # print(audio_path)
            pbar.set_postfix({'status': f'Processed {fname}'})
            
        except Exception as e:
            print(f"\nError processing {fname}: {str(e)}")
            continue

# 输入输出路径配置
input_dirs = [
    (params_paths['test_audio_input'], params_paths['test_feature_extracted']),  # (输入目录, 输出目录)
    # (params_paths['train_audio_input'], params_paths['train_feature_extracted']),  # (输入目录, 输出目录)
]

# 处理所有输入目录
for input_dir, output_dir in input_dirs:
    print(f"\nStarting feature extraction from {input_dir} to {output_dir}")
    extract_features(input_dir, output_dir, force_reprocess=False)
    print(f"Feature extraction from {input_dir} completed!")

print("\nAll feature extraction tasks finished!")


Starting feature extraction from ../fsd18kdataset/FSDnoisy18k.audio_test to ../features/audio_test_varup2
所有特征文件已存在，无需处理
Feature extraction from ../fsd18kdataset/FSDnoisy18k.audio_test completed!

All feature extraction tasks finished!


In [5]:

# mel_spec_test_path = "./features/audio_test_varup2"     # (输入目录, 输出目录)
# mel_spec_train_path = "./features/audio_train_varup2"    # (输入目录, 输出目录)

# dataset = 'FSDnoisy18k'
# train_dataset_path = ./fsd18kdataset/FSDnoisy18k.audio_train
# test_dataset_path =./fsd18kdataset/FSDnoisy18k.audio_test
# train_csv_path =./fsd18kdataset/FSDnoisy18k.meta/train.csv
# test_csv_path =./fsd18kdataset/FSDnoisy18k.meta/test.csv

In [6]:
import os

# 设置特征目录
feature_dir = params_paths['test_feature_extracted']

# 获取前5个特征文件
data_files = [f for f in os.listdir(feature_dir) if f.endswith('_mel.data')][:20]

# 读取并打印特征和标签
for data_file in data_files:
    # 构建完整路径
    base_path = os.path.join(feature_dir, data_file.replace('_mel.data', ''))
    
    # 读取特征
    features = utils.load_tensor(base_path + '.data', suffix='_mel')
    
    # 读取标签
    labels = utils.load_tensor(base_path + '.data', suffix='_label')
    
    print(f"\n文件: {data_file}")
    print(f"特征形状: {features.shape}, 数据类型: {features.dtype}")
    print(f"标签值: {labels}")
    print("特征数据片段:")
    print(features[:2, :5])  # 打印前2帧的前5个特征值


文件: 119132_mel.data
特征形状: (453, 96), 数据类型: float64
标签值: [17.]
特征数据片段:
[[1.4527321  2.17643304 1.85556236 1.72903471 1.11300528]
 [3.56286856 2.5534014  1.96680357 1.89257999 1.49813842]]

文件: 83133_mel.data
特征形状: (483, 96), 数据类型: float64
标签值: [12.]
特征数据片段:
[[1.1759873  1.50689617 1.5857191  1.39692153 1.86449286]
 [1.29114257 1.22856175 1.72177464 1.7587213  1.27283517]]

文件: 173719_mel.data
特征形状: (501, 96), 数据类型: float64
标签值: [12.]
特征数据片段:
[[0.15754306 1.34155552 1.74122783 1.56484479 2.43530863]
 [2.18153018 1.72870499 2.31905241 2.09167365 2.38353328]]

文件: 386879_mel.data
特征形状: (152, 96), 数据类型: float64
标签值: [17.]
特征数据片段:
[[ 0.24897278 -0.29169804 -1.22542622 -1.17504196 -1.35474821]
 [ 1.29924828  0.44491568 -0.1034484  -0.37548224 -0.27222024]]

文件: 414515_mel.data
特征形状: (255, 96), 数据类型: float64
标签值: [9.]
特征数据片段:
[[-3.45425735 -4.31198369 -4.73791996 -5.00848544 -5.21129158]
 [-3.43148458 -6.52460992 -7.04592305 -7.62572807 -7.08303259]]

文件: 324760_mel.data
特征形状: (152, 96), 数据类型

In [7]:
# import numpy as np
from data import DataGeneratorPatch
from torch.utils.data import Dataset, DataLoader
import torch


class TorchDataWrapper(Dataset):
    def __init__(self, keras_data_gen):
        self.keras_gen = keras_data_gen
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        
    def __len__(self):
        return len(self.keras_gen)
    
    def __getitem__(self, idx):
        features, labels = self.keras_gen[idx]
        return (
            torch.from_numpy(features).float().to(self.device),
            torch.from_numpy(labels.argmax(1)).long().to(self.device)
        )




# 初始化数据生成器
feature_dir = params_paths['test_feature_extracted']
file_list = [f for f in os.listdir(feature_dir) if f.endswith('_mel.data')]

print(f"wenjianliebiao:{file_list},\n 特征文件数量: {len(file_list)}\n")
data_gen = DataGeneratorPatch(
    feature_dir=feature_dir,
    file_list=file_list,
    params_learn=params_learn,
    params_extract=params_extract,
    suffix_in='_mel',
    suffix_out='_label'
)

# 创建PyTorch兼容的数据集
torch_dataset = TorchDataWrapper(data_gen)

# 创建PyTorch DataLoader
train_loader = DataLoader(
    torch_dataset,
    batch_size=None,  # 因为原作者已处理批次
    shuffle=True,
    num_workers=0,
    pin_memory=True if torch.cuda.is_available() else False
)

# 获取并打印第一个batch
for batch_idx, (features, labels) in enumerate(train_loader):
    print(f"\nPyTorch DataLoader 第一个batch:")
    print(f"特征张量形状: {features.shape}")  # 应该是 [batch, 1, time, freq]
    print(f"标签张量形状: {labels.shape}")    # 应该是 [batch]
    
    # 打印第一个样本的部分数据
    print("\n第一个样本的特征数据(部分):")
    print(features[0, 0, :5, :5])  # 打印第一个样本的5x5片段
    
    print("\n所有样本的标签:")
    print(labels)
    
    break  # 只查看第一个batch

for batch_idx, (features, labels) in enumerate(train_loader):
    print(f"\nPyTorch DataLoader 第一个batch:")
    print(f"特征张量形状: {features.shape}")  # [batch, 1, time, freq]
    print(f"标签张量形状: {labels.shape}")    # [batch]
    for i in range(features.shape[0]):
        print(f"\n样本{i} 标签: {labels[i].item()}")
        print(f"样本{i} 特征片段:\n{features[i, 0, :5, :5]}")
    break


wenjianliebiao:['119132_mel.data', '83133_mel.data', '173719_mel.data', '386879_mel.data', '414515_mel.data', '324760_mel.data', '348024_mel.data', '128797_mel.data', '153427_mel.data', '69732_mel.data', '61644_mel.data', '52289_mel.data', '152983_mel.data', '46280_mel.data', '235535_mel.data', '186767_mel.data', '564_mel.data', '238955_mel.data', '266484_mel.data', '173062_mel.data', '178615_mel.data', '44965_mel.data', '253614_mel.data', '135034_mel.data', '263116_mel.data', '69487_mel.data', '160790_mel.data', '372470_mel.data', '378400_mel.data', '62527_mel.data', '67786_mel.data', '267956_mel.data', '23218_mel.data', '38594_mel.data', '379016_mel.data', '116977_mel.data', '379017_mel.data', '253807_mel.data', '45642_mel.data', '68954_mel.data', '213307_mel.data', '102789_mel.data', '379893_mel.data', '181425_mel.data', '40290_mel.data', '197383_mel.data', '136690_mel.data', '381855_mel.data', '180980_mel.data', '136691_mel.data', '171996_mel.data', '57800_mel.data', '232988_mel.da

In [8]:
from baseline_cnn import BaselineCNN
from torch import nn

from tqdm import tqdm
from torch.utils.tensorboard import SummaryWriter

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


print("BaselineCNN imported successfully!")
model = BaselineCNN(
    n_mels=params_extract['n_mels'],
    patch_len=params_extract['patch_len'],
    n_classes=params_learn['n_classes']
).to(device)

# 添加模型权重加载功能
pretrained_path = params_paths['pretrained']  # 替换为你的预训练模型路径
if os.path.exists(pretrained_path):
    model.load_state_dict(torch.load(pretrained_path))
    print('成功加载预训练权重')
else:
    print('未找到预训练模型，将从零开始训练')


print('loading optimizer and loss function...')
# 定义优化器和损失函数
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-3  # L2正则化
)
criterion = nn.CrossEntropyLoss()
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, 
    mode='max',  # 监控验证准确率
    factor=0.5,
    patience=5,
    verbose=True
)


# 添加检查点恢复功能
checkpoint_path = 'interrupted_checkpoint.pth'
start_epoch = 0
if os.path.exists(checkpoint_path):
    checkpoint = torch.load(checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    start_epoch = checkpoint['epoch']
    best_acc = checkpoint['best_acc']
    print(f'从检查点恢复训练，epoch={start_epoch}, 最佳准确率={best_acc:.4f}')


# 创建TensorBoard writer
writer = SummaryWriter()

# 训练循环
def train(model, loader, optimizer, criterion, epochs=160):
    model.train()
    best_acc = 0.0

    # 添加检查点目录
    os.makedirs('checkpoints', exist_ok=True)

    # 添加epoch进度条
    epoch_pbar = tqdm(range(epochs), desc='Training', unit='epoch')

    for epoch in epoch_pbar:
        try:
            total_loss = 0
            correct = 0
            # 添加batch进度条
            batch_pbar = tqdm(loader, desc=f'Epoch {epoch+1}', leave=False)
            for features, labels in batch_pbar:
                optimizer.zero_grad()
                
                # 前向传播
                outputs = model(features)
                loss = criterion(outputs, labels.squeeze())
                
                # 反向传播
                loss.backward()
                optimizer.step()
                
                # 统计
                total_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                correct += (predicted == labels.squeeze()).sum().item()

                # 更新batch进度条
                batch_pbar.set_postfix(loss=loss.item())
            
            # 计算epoch统计
            avg_loss = total_loss / len(loader)
            accuracy = correct / len(loader.dataset)

             # 记录到TensorBoard
            writer.add_scalar('Loss/train', avg_loss, epoch)
            writer.add_scalar('Accuracy/train', accuracy, epoch)

            # 更新学习率
            scheduler.step(accuracy)

            # 保存最佳模型
            if accuracy > best_acc:
                best_acc = accuracy
                torch.save(model.state_dict(), 'best_model.pth')
                print(f'保存最佳模型，准确率: {accuracy:.4f}')
            print(f'Epoch {epoch+1}: Loss={avg_loss:.4f}, Accuracy={accuracy:.4f}')

            # 更新epoch进度条
            epoch_pbar.set_postfix(loss=avg_loss, acc=accuracy)

            # # 保存检查点(每个epoch都保存)
            # checkpoint_path = f'checkpoints/epoch_{epoch+1}.pth'
            # torch.save({
            #     'epoch': epoch+1,
            #     'model_state_dict': model.state_dict(),
            #     'optimizer_state_dict': optimizer.state_dict(),
            #     'best_acc': best_acc,
            #     'loss': avg_loss,
            # }, checkpoint_path)
        except KeyboardInterrupt:
            print("\n训练被中断，正在保存当前状态...")
            torch.save({
                'epoch': epoch+1,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'best_acc': best_acc,
                'loss': avg_loss,
            }, 'interrupted_checkpoint.pth')
            print("已保存中断检查点到 interrupted_checkpoint.pth")
            return

    # 训练结束后保存最终模型
    # torch.save(model.state_dict(), 'final_model.pth')
    # print('训练完成，最终模型已保存')
    writer.close()
    torch.save(model.state_dict(), 'final_model.pth')
    epoch_pbar.write('训练完成，最终模型已保存')

print('training started...')

# 开始训练
train(model, train_loader, optimizer, criterion)

BaselineCNN imported successfully!
未找到预训练模型，将从零开始训练
loading optimizer and loss function...


/Users/nadinebrewington/miniforge3/envs/py38/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


training started...


Training:   1%|          | 1/160 [00:18<48:35, 18.34s/epoch, acc=5.09, loss=12]

保存最佳模型，准确率: 5.0882
Epoch 1: Loss=12.0455, Accuracy=5.0882


Training:   1%|▏         | 2/160 [00:36<48:03, 18.25s/epoch, acc=7.69, loss=3.07]

保存最佳模型，准确率: 7.6912
Epoch 2: Loss=3.0746, Accuracy=7.6912


Training:   2%|▏         | 3/160 [00:54<47:17, 18.07s/epoch, acc=8.01, loss=3]   

保存最佳模型，准确率: 8.0147
Epoch 3: Loss=3.0006, Accuracy=8.0147


Training:   2%|▎         | 4/160 [01:12<47:03, 18.10s/epoch, acc=8.13, loss=2.99]

保存最佳模型，准确率: 8.1324
Epoch 4: Loss=2.9902, Accuracy=8.1324


Training:   3%|▎         | 5/160 [01:33<49:02, 18.98s/epoch, acc=8.12, loss=2.95]

Epoch 5: Loss=2.9473, Accuracy=8.1176


Training:   4%|▍         | 6/160 [01:52<49:32, 19.30s/epoch, acc=8.84, loss=2.91]

保存最佳模型，准确率: 8.8382
Epoch 6: Loss=2.9099, Accuracy=8.8382


Training:   4%|▍         | 7/160 [02:13<49:51, 19.55s/epoch, acc=9.01, loss=2.9] 

保存最佳模型，准确率: 9.0147
Epoch 7: Loss=2.9013, Accuracy=9.0147


Training:   5%|▌         | 8/160 [02:32<49:48, 19.66s/epoch, acc=9.4, loss=2.88]

保存最佳模型，准确率: 9.3971
Epoch 8: Loss=2.8776, Accuracy=9.3971


Training:   6%|▌         | 9/160 [02:52<49:43, 19.76s/epoch, acc=9.75, loss=2.84]

保存最佳模型，准确率: 9.7500
Epoch 9: Loss=2.8419, Accuracy=9.7500


Training:   6%|▋         | 10/160 [03:13<50:16, 20.11s/epoch, acc=9.75, loss=2.82]

Epoch 10: Loss=2.8204, Accuracy=9.7500


Training:   7%|▋         | 11/160 [03:36<51:31, 20.75s/epoch, acc=9.81, loss=2.82]

保存最佳模型，准确率: 9.8088
Epoch 11: Loss=2.8230, Accuracy=9.8088


Training:   8%|▊         | 12/160 [03:57<51:26, 20.85s/epoch, acc=9.94, loss=2.8] 

保存最佳模型，准确率: 9.9412
Epoch 12: Loss=2.8006, Accuracy=9.9412


Training:   8%|▊         | 13/160 [04:18<51:39, 21.08s/epoch, acc=10.2, loss=2.76]

保存最佳模型，准确率: 10.1618
Epoch 13: Loss=2.7629, Accuracy=10.1618


Training:   9%|▉         | 14/160 [04:39<51:00, 20.96s/epoch, acc=10.4, loss=2.74]

保存最佳模型，准确率: 10.4118
Epoch 14: Loss=2.7399, Accuracy=10.4118


Training:   9%|▉         | 15/160 [04:59<49:55, 20.66s/epoch, acc=10.2, loss=2.73]

Epoch 15: Loss=2.7329, Accuracy=10.2500


Training:  10%|█         | 16/160 [05:20<49:44, 20.72s/epoch, acc=10.2, loss=2.69]

Epoch 16: Loss=2.6875, Accuracy=10.1912


Training:  11%|█         | 17/160 [05:40<49:19, 20.70s/epoch, acc=10.3, loss=2.66]

Epoch 17: Loss=2.6592, Accuracy=10.2794


Training:  11%|█▏        | 18/160 [06:01<48:40, 20.57s/epoch, acc=9.99, loss=2.66]

Epoch 18: Loss=2.6601, Accuracy=9.9853


Training:  12%|█▏        | 19/160 [06:21<48:02, 20.45s/epoch, acc=10.1, loss=2.65]

Epoch 19: Loss=2.6489, Accuracy=10.0588


Training:  12%|█▎        | 20/160 [06:41<47:40, 20.43s/epoch, acc=10.3, loss=2.62]

Epoch 20: Loss=2.6203, Accuracy=10.3088


Training:  13%|█▎        | 21/160 [07:02<47:48, 20.64s/epoch, acc=10.2, loss=2.64]

Epoch 21: Loss=2.6350, Accuracy=10.2059


Training:  14%|█▍        | 22/160 [07:24<48:01, 20.88s/epoch, acc=10.8, loss=2.6] 

保存最佳模型，准确率: 10.7794
Epoch 22: Loss=2.5982, Accuracy=10.7794


Training:  14%|█▍        | 23/160 [07:44<47:32, 20.82s/epoch, acc=10.5, loss=2.6]

Epoch 23: Loss=2.5959, Accuracy=10.4853


Training:  15%|█▌        | 24/160 [08:05<47:04, 20.77s/epoch, acc=10.9, loss=2.58]

保存最佳模型，准确率: 10.8529
Epoch 24: Loss=2.5794, Accuracy=10.8529


Training:  16%|█▌        | 25/160 [08:26<46:50, 20.82s/epoch, acc=10.6, loss=2.58]

Epoch 25: Loss=2.5752, Accuracy=10.5588


Training:  16%|█▋        | 26/160 [08:47<46:46, 20.94s/epoch, acc=10.9, loss=2.58]

保存最佳模型，准确率: 10.9118
Epoch 26: Loss=2.5782, Accuracy=10.9118


Training:  17%|█▋        | 27/160 [09:09<46:50, 21.13s/epoch, acc=11.2, loss=2.56]

保存最佳模型，准确率: 11.2059
Epoch 27: Loss=2.5593, Accuracy=11.2059


Training:  18%|█▊        | 28/160 [09:31<46:59, 21.36s/epoch, acc=11.2, loss=2.55]

Epoch 28: Loss=2.5513, Accuracy=11.1765


Training:  18%|█▊        | 29/160 [09:53<47:14, 21.64s/epoch, acc=11.5, loss=2.56]

保存最佳模型，准确率: 11.5441
Epoch 29: Loss=2.5603, Accuracy=11.5441


Training:  19%|█▉        | 30/160 [10:15<47:10, 21.77s/epoch, acc=11.8, loss=2.53]

保存最佳模型，准确率: 11.7500
Epoch 30: Loss=2.5311, Accuracy=11.7500


Training:  19%|█▉        | 31/160 [10:37<46:59, 21.85s/epoch, acc=13.2, loss=2.51]

保存最佳模型，准确率: 13.2206
Epoch 31: Loss=2.5122, Accuracy=13.2206


Training:  20%|██        | 32/160 [11:03<49:01, 22.98s/epoch, acc=14.2, loss=2.5] 

保存最佳模型，准确率: 14.1618
Epoch 32: Loss=2.4979, Accuracy=14.1618


Training:  21%|██        | 33/160 [11:26<48:38, 22.98s/epoch, acc=14.2, loss=2.5]

保存最佳模型，准确率: 14.2500
Epoch 33: Loss=2.4959, Accuracy=14.2500


Training:  21%|██▏       | 34/160 [11:48<47:37, 22.68s/epoch, acc=14.6, loss=2.47]

保存最佳模型，准确率: 14.6471
Epoch 34: Loss=2.4692, Accuracy=14.6471


Training:  22%|██▏       | 35/160 [12:10<47:05, 22.60s/epoch, acc=15.1, loss=2.48]

保存最佳模型，准确率: 15.1029
Epoch 35: Loss=2.4756, Accuracy=15.1029


Training:  22%|██▎       | 36/160 [12:33<47:05, 22.79s/epoch, acc=16, loss=2.41]  

保存最佳模型，准确率: 15.9706
Epoch 36: Loss=2.4136, Accuracy=15.9706


Training:  23%|██▎       | 37/160 [12:55<46:11, 22.53s/epoch, acc=16.2, loss=2.42]

保存最佳模型，准确率: 16.2059
Epoch 37: Loss=2.4211, Accuracy=16.2059


Training:  24%|██▍       | 38/160 [13:17<45:12, 22.24s/epoch, acc=16.4, loss=2.41]

保存最佳模型，准确率: 16.4118
Epoch 38: Loss=2.4063, Accuracy=16.4118


Training:  24%|██▍       | 39/160 [13:39<44:52, 22.26s/epoch, acc=17, loss=2.4]   

保存最佳模型，准确率: 16.9559
Epoch 39: Loss=2.4044, Accuracy=16.9559


Training:  25%|██▌       | 40/160 [14:01<44:13, 22.12s/epoch, acc=17.4, loss=2.37]

保存最佳模型，准确率: 17.4265
Epoch 40: Loss=2.3661, Accuracy=17.4265


Training:  26%|██▌       | 41/160 [14:23<43:52, 22.12s/epoch, acc=18.1, loss=2.32]

保存最佳模型，准确率: 18.0735
Epoch 41: Loss=2.3222, Accuracy=18.0735


Training:  26%|██▋       | 42/160 [14:44<42:57, 21.84s/epoch, acc=18.6, loss=2.32]

保存最佳模型，准确率: 18.5588
Epoch 42: Loss=2.3199, Accuracy=18.5588


Training:  27%|██▋       | 43/160 [15:05<42:05, 21.58s/epoch, acc=19.6, loss=2.28]

保存最佳模型，准确率: 19.5588
Epoch 43: Loss=2.2829, Accuracy=19.5588


Training:  28%|██▊       | 44/160 [15:26<41:25, 21.43s/epoch, acc=20.5, loss=2.25]

保存最佳模型，准确率: 20.4853
Epoch 44: Loss=2.2516, Accuracy=20.4853


Training:  28%|██▊       | 45/160 [15:47<40:42, 21.24s/epoch, acc=20.7, loss=2.25]

保存最佳模型，准确率: 20.6765
Epoch 45: Loss=2.2532, Accuracy=20.6765


Training:  29%|██▉       | 46/160 [16:08<40:05, 21.10s/epoch, acc=21.3, loss=2.19]

保存最佳模型，准确率: 21.3088
Epoch 46: Loss=2.1921, Accuracy=21.3088


Training:  29%|██▉       | 47/160 [16:29<39:37, 21.04s/epoch, acc=21.8, loss=2.19]

保存最佳模型，准确率: 21.8382
Epoch 47: Loss=2.1869, Accuracy=21.8382


Training:  30%|███       | 48/160 [16:50<39:07, 20.96s/epoch, acc=22.2, loss=2.14]

保存最佳模型，准确率: 22.2059
Epoch 48: Loss=2.1384, Accuracy=22.2059


Training:  31%|███       | 49/160 [17:10<38:43, 20.93s/epoch, acc=23, loss=2.11]  

保存最佳模型，准确率: 22.9853
Epoch 49: Loss=2.1085, Accuracy=22.9853


Training:  31%|███▏      | 50/160 [17:32<38:55, 21.23s/epoch, acc=23.4, loss=2.08]

保存最佳模型，准确率: 23.4118
Epoch 50: Loss=2.0797, Accuracy=23.4118


Training:  32%|███▏      | 51/160 [17:54<38:40, 21.28s/epoch, acc=23.4, loss=2.06]

Epoch 51: Loss=2.0562, Accuracy=23.3529


Training:  32%|███▎      | 52/160 [18:16<38:51, 21.59s/epoch, acc=24.2, loss=2.03]

保存最佳模型，准确率: 24.2353
Epoch 52: Loss=2.0338, Accuracy=24.2353


Training:  33%|███▎      | 53/160 [18:39<39:01, 21.88s/epoch, acc=23.9, loss=2.06]

Epoch 53: Loss=2.0561, Accuracy=23.9118


Training:  34%|███▍      | 54/160 [19:01<38:50, 21.99s/epoch, acc=25.1, loss=1.99]

保存最佳模型，准确率: 25.1176
Epoch 54: Loss=1.9877, Accuracy=25.1176


Training:  34%|███▍      | 55/160 [19:23<38:22, 21.93s/epoch, acc=25.8, loss=1.97]

保存最佳模型，准确率: 25.7794
Epoch 55: Loss=1.9670, Accuracy=25.7794


Training:  35%|███▌      | 56/160 [19:45<38:01, 21.94s/epoch, acc=26.2, loss=1.94]

保存最佳模型，准确率: 26.1618
Epoch 56: Loss=1.9354, Accuracy=26.1618


Training:  36%|███▌      | 57/160 [20:06<37:16, 21.71s/epoch, acc=26.5, loss=1.94]

保存最佳模型，准确率: 26.4706
Epoch 57: Loss=1.9371, Accuracy=26.4706


Training:  36%|███▋      | 58/160 [20:27<36:43, 21.61s/epoch, acc=27.4, loss=1.88]

保存最佳模型，准确率: 27.3676
Epoch 58: Loss=1.8841, Accuracy=27.3676


Training:  37%|███▋      | 59/160 [20:52<37:46, 22.44s/epoch, acc=28.3, loss=1.85]

保存最佳模型，准确率: 28.2941
Epoch 59: Loss=1.8471, Accuracy=28.2941


Training:  38%|███▊      | 60/160 [21:13<36:54, 22.15s/epoch, acc=28.2, loss=1.82]

Epoch 60: Loss=1.8229, Accuracy=28.2059


Training:  38%|███▊      | 61/160 [21:35<36:24, 22.07s/epoch, acc=28.8, loss=1.8] 

保存最佳模型，准确率: 28.8235
Epoch 61: Loss=1.7978, Accuracy=28.8235


Training:  39%|███▉      | 62/160 [21:56<35:25, 21.69s/epoch, acc=29.6, loss=1.76]

保存最佳模型，准确率: 29.6029
Epoch 62: Loss=1.7595, Accuracy=29.6029


Training:  39%|███▉      | 63/160 [22:18<35:14, 21.80s/epoch, acc=29.2, loss=1.77]

Epoch 63: Loss=1.7723, Accuracy=29.2353


Training:  40%|████      | 64/160 [22:40<35:14, 22.02s/epoch, acc=30.2, loss=1.73]

保存最佳模型，准确率: 30.1912
Epoch 64: Loss=1.7266, Accuracy=30.1912


Training:  41%|████      | 65/160 [23:02<34:33, 21.83s/epoch, acc=30.5, loss=1.72]

保存最佳模型，准确率: 30.5294
Epoch 65: Loss=1.7180, Accuracy=30.5294


Training:  41%|████▏     | 66/160 [23:23<34:07, 21.78s/epoch, acc=31, loss=1.69]  

保存最佳模型，准确率: 30.9853
Epoch 66: Loss=1.6894, Accuracy=30.9853


Training:  42%|████▏     | 67/160 [23:45<33:30, 21.62s/epoch, acc=31.7, loss=1.64]

保存最佳模型，准确率: 31.7206
Epoch 67: Loss=1.6365, Accuracy=31.7206


Training:  42%|████▎     | 68/160 [24:06<33:08, 21.61s/epoch, acc=31.6, loss=1.63]

Epoch 68: Loss=1.6256, Accuracy=31.5882


Training:  43%|████▎     | 69/160 [24:29<33:07, 21.84s/epoch, acc=33.1, loss=1.56]

保存最佳模型，准确率: 33.1471
Epoch 69: Loss=1.5583, Accuracy=33.1471


Training:  44%|████▍     | 70/160 [24:50<32:44, 21.83s/epoch, acc=33.2, loss=1.55]

保存最佳模型，准确率: 33.1618
Epoch 70: Loss=1.5468, Accuracy=33.1618


Training:  44%|████▍     | 71/160 [25:12<32:20, 21.80s/epoch, acc=33.8, loss=1.51]

保存最佳模型，准确率: 33.7647
Epoch 71: Loss=1.5079, Accuracy=33.7647


Training:  45%|████▌     | 72/160 [25:33<31:47, 21.67s/epoch, acc=34.6, loss=1.47]

保存最佳模型，准确率: 34.5882
Epoch 72: Loss=1.4693, Accuracy=34.5882


Training:  46%|████▌     | 73/160 [25:55<31:09, 21.49s/epoch, acc=34.8, loss=1.44]

保存最佳模型，准确率: 34.7941
Epoch 73: Loss=1.4393, Accuracy=34.7941


Training:  46%|████▋     | 74/160 [26:16<30:35, 21.34s/epoch, acc=35.1, loss=1.42]

保存最佳模型，准确率: 35.0588
Epoch 74: Loss=1.4169, Accuracy=35.0588


Training:  47%|████▋     | 75/160 [26:36<30:05, 21.24s/epoch, acc=36.1, loss=1.37]

保存最佳模型，准确率: 36.1176
Epoch 75: Loss=1.3727, Accuracy=36.1176


Training:  48%|████▊     | 76/160 [26:58<29:53, 21.35s/epoch, acc=37.1, loss=1.33]

保存最佳模型，准确率: 37.0735
Epoch 76: Loss=1.3327, Accuracy=37.0735


Training:  48%|████▊     | 77/160 [27:19<29:30, 21.33s/epoch, acc=37.2, loss=1.3] 

保存最佳模型，准确率: 37.2500
Epoch 77: Loss=1.2991, Accuracy=37.2500


Training:  49%|████▉     | 78/160 [27:41<29:05, 21.29s/epoch, acc=37.8, loss=1.28]

保存最佳模型，准确率: 37.7647
Epoch 78: Loss=1.2829, Accuracy=37.7647


Training:  49%|████▉     | 79/160 [28:02<28:41, 21.25s/epoch, acc=39.3, loss=1.23]

保存最佳模型，准确率: 39.3235
Epoch 79: Loss=1.2283, Accuracy=39.3235


Training:  50%|█████     | 80/160 [28:23<28:23, 21.30s/epoch, acc=39.3, loss=1.19]

Epoch 80: Loss=1.1932, Accuracy=39.3235


Training:  51%|█████     | 81/160 [28:46<28:48, 21.88s/epoch, acc=40.6, loss=1.17]

保存最佳模型，准确率: 40.6471
Epoch 81: Loss=1.1701, Accuracy=40.6471


Training:  51%|█████▏    | 82/160 [29:10<29:03, 22.35s/epoch, acc=41.7, loss=1.11]

保存最佳模型，准确率: 41.7059
Epoch 82: Loss=1.1056, Accuracy=41.7059


Training:  52%|█████▏    | 83/160 [29:36<30:19, 23.63s/epoch, acc=41.2, loss=1.12]

Epoch 83: Loss=1.1219, Accuracy=41.2500


Training:  52%|█████▎    | 84/160 [30:02<30:31, 24.09s/epoch, acc=42.1, loss=1.07]

保存最佳模型，准确率: 42.1471
Epoch 84: Loss=1.0667, Accuracy=42.1471


Training:  53%|█████▎    | 85/160 [30:25<29:42, 23.77s/epoch, acc=42.4, loss=1.07]

保存最佳模型，准确率: 42.4412
Epoch 85: Loss=1.0729, Accuracy=42.4412


Training:  54%|█████▍    | 86/160 [30:47<28:55, 23.45s/epoch, acc=44.1, loss=0.991]

保存最佳模型，准确率: 44.1029
Epoch 86: Loss=0.9906, Accuracy=44.1029


Training:  54%|█████▍    | 87/160 [31:10<28:05, 23.09s/epoch, acc=43.6, loss=0.972]

Epoch 87: Loss=0.9719, Accuracy=43.5882


Training:  55%|█████▌    | 88/160 [31:32<27:37, 23.02s/epoch, acc=45.1, loss=0.922]

保存最佳模型，准确率: 45.1471
Epoch 88: Loss=0.9220, Accuracy=45.1471


Training:  56%|█████▌    | 89/160 [31:55<27:02, 22.85s/epoch, acc=45, loss=0.924]  

Epoch 89: Loss=0.9239, Accuracy=45.0294


Training:  56%|█████▋    | 90/160 [32:17<26:25, 22.65s/epoch, acc=45.6, loss=0.89]

保存最佳模型，准确率: 45.6176
Epoch 90: Loss=0.8897, Accuracy=45.6176


Training:  57%|█████▋    | 91/160 [32:40<26:03, 22.66s/epoch, acc=46.9, loss=0.855]

保存最佳模型，准确率: 46.8824
Epoch 91: Loss=0.8549, Accuracy=46.8824


Training:  57%|█████▊    | 92/160 [33:02<25:37, 22.62s/epoch, acc=47.1, loss=0.831]

保存最佳模型，准确率: 47.0588
Epoch 92: Loss=0.8309, Accuracy=47.0588


Training:  58%|█████▊    | 93/160 [33:25<25:12, 22.58s/epoch, acc=46.8, loss=0.834]

Epoch 93: Loss=0.8338, Accuracy=46.7500


Training:  59%|█████▉    | 94/160 [33:47<24:51, 22.60s/epoch, acc=48, loss=0.78]   

保存最佳模型，准确率: 48.0000
Epoch 94: Loss=0.7796, Accuracy=48.0000


Training:  59%|█████▉    | 95/160 [34:11<24:50, 22.94s/epoch, acc=48.3, loss=0.771]

保存最佳模型，准确率: 48.2794
Epoch 95: Loss=0.7706, Accuracy=48.2794


Training:  60%|██████    | 96/160 [34:33<24:03, 22.55s/epoch, acc=48.6, loss=0.753]

保存最佳模型，准确率: 48.5588
Epoch 96: Loss=0.7530, Accuracy=48.5588


Training:  61%|██████    | 97/160 [34:54<23:13, 22.11s/epoch, acc=48.9, loss=0.735]

保存最佳模型，准确率: 48.9265
Epoch 97: Loss=0.7350, Accuracy=48.9265


Training:  61%|██████▏   | 98/160 [35:16<22:46, 22.04s/epoch, acc=49.8, loss=0.693]

保存最佳模型，准确率: 49.7500
Epoch 98: Loss=0.6929, Accuracy=49.7500


Training:  62%|██████▏   | 99/160 [35:38<22:21, 21.99s/epoch, acc=48.9, loss=0.721]

Epoch 99: Loss=0.7207, Accuracy=48.9265


Training:  62%|██████▎   | 100/160 [36:01<22:18, 22.31s/epoch, acc=50.5, loss=0.656]

保存最佳模型，准确率: 50.5000
Epoch 100: Loss=0.6560, Accuracy=50.5000


Training:  63%|██████▎   | 101/160 [36:23<21:56, 22.31s/epoch, acc=50.4, loss=0.661]

Epoch 101: Loss=0.6608, Accuracy=50.4265


Training:  64%|██████▍   | 102/160 [36:44<21:14, 21.97s/epoch, acc=50.8, loss=0.657]

保存最佳模型，准确率: 50.7794
Epoch 102: Loss=0.6574, Accuracy=50.7794


Training:  64%|██████▍   | 103/160 [37:06<20:55, 22.02s/epoch, acc=51.7, loss=0.597]

保存最佳模型，准确率: 51.6618
Epoch 103: Loss=0.5970, Accuracy=51.6618


Training:  65%|██████▌   | 104/160 [37:30<21:01, 22.52s/epoch, acc=50.8, loss=0.645]

Epoch 104: Loss=0.6450, Accuracy=50.7500


Training:  66%|██████▌   | 105/160 [37:52<20:25, 22.29s/epoch, acc=51.8, loss=0.586]

保存最佳模型，准确率: 51.7794
Epoch 105: Loss=0.5859, Accuracy=51.7794


Training:  66%|██████▋   | 106/160 [38:13<19:50, 22.04s/epoch, acc=53.2, loss=0.528]

保存最佳模型，准确率: 53.2500
Epoch 106: Loss=0.5283, Accuracy=53.2500


Training:  67%|██████▋   | 107/160 [38:37<19:50, 22.47s/epoch, acc=53.3, loss=0.513]

保存最佳模型，准确率: 53.2647
Epoch 107: Loss=0.5125, Accuracy=53.2647


Training:  68%|██████▊   | 108/160 [38:58<19:15, 22.21s/epoch, acc=53.2, loss=0.531]

Epoch 108: Loss=0.5305, Accuracy=53.2353


Training:  68%|██████▊   | 109/160 [39:20<18:43, 22.03s/epoch, acc=53.4, loss=0.504]

保存最佳模型，准确率: 53.4118
Epoch 109: Loss=0.5044, Accuracy=53.4118


Training:  69%|██████▉   | 110/160 [39:42<18:29, 22.18s/epoch, acc=54.7, loss=0.46] 

保存最佳模型，准确率: 54.7059
Epoch 110: Loss=0.4599, Accuracy=54.7059


Training:  69%|██████▉   | 111/160 [40:06<18:32, 22.70s/epoch, acc=53.8, loss=0.493]

Epoch 111: Loss=0.4931, Accuracy=53.7500


Training:  70%|███████   | 112/160 [40:29<18:02, 22.55s/epoch, acc=55, loss=0.444]  

保存最佳模型，准确率: 55.0000
Epoch 112: Loss=0.4441, Accuracy=55.0000


Training:  71%|███████   | 113/160 [40:50<17:29, 22.33s/epoch, acc=54.8, loss=0.448]

Epoch 113: Loss=0.4482, Accuracy=54.7941


Training:  71%|███████▏  | 114/160 [41:13<17:10, 22.39s/epoch, acc=55, loss=0.434]  

保存最佳模型，准确率: 55.0441
Epoch 114: Loss=0.4342, Accuracy=55.0441


Training:  72%|███████▏  | 115/160 [41:36<17:00, 22.67s/epoch, acc=56, loss=0.4]  

保存最佳模型，准确率: 56.0000
Epoch 115: Loss=0.4000, Accuracy=56.0000


Training:  72%|███████▎  | 116/160 [41:58<16:29, 22.48s/epoch, acc=55.9, loss=0.411]

Epoch 116: Loss=0.4107, Accuracy=55.8824


Training:  73%|███████▎  | 117/160 [42:21<16:09, 22.54s/epoch, acc=55.1, loss=0.42] 

Epoch 117: Loss=0.4200, Accuracy=55.0588


Training:  74%|███████▍  | 118/160 [42:43<15:38, 22.34s/epoch, acc=55.4, loss=0.41]

Epoch 118: Loss=0.4098, Accuracy=55.4412


Training:  74%|███████▍  | 119/160 [43:06<15:25, 22.57s/epoch, acc=56.1, loss=0.388]

保存最佳模型，准确率: 56.0588
Epoch 119: Loss=0.3878, Accuracy=56.0588


Training:  75%|███████▌  | 120/160 [43:29<15:05, 22.65s/epoch, acc=56, loss=0.381]  

Epoch 120: Loss=0.3808, Accuracy=56.0441


Training:  76%|███████▌  | 121/160 [43:52<14:51, 22.87s/epoch, acc=56.1, loss=0.388]

保存最佳模型，准确率: 56.0882
Epoch 121: Loss=0.3877, Accuracy=56.0882


Training:  76%|███████▋  | 122/160 [44:15<14:27, 22.84s/epoch, acc=56.6, loss=0.353]

保存最佳模型，准确率: 56.5882
Epoch 122: Loss=0.3532, Accuracy=56.5882


Training:  77%|███████▋  | 123/160 [44:37<13:57, 22.62s/epoch, acc=56.6, loss=0.347]

Epoch 123: Loss=0.3467, Accuracy=56.5882


Training:  78%|███████▊  | 124/160 [45:00<13:37, 22.72s/epoch, acc=56.7, loss=0.344]

保存最佳模型，准确率: 56.7059
Epoch 124: Loss=0.3438, Accuracy=56.7059


Training:  78%|███████▊  | 125/160 [45:24<13:25, 23.01s/epoch, acc=56.5, loss=0.367]

Epoch 125: Loss=0.3667, Accuracy=56.5294


Training:  79%|███████▉  | 126/160 [45:47<13:04, 23.07s/epoch, acc=57, loss=0.339]  

保存最佳模型，准确率: 56.9853
Epoch 126: Loss=0.3388, Accuracy=56.9853


Training:  79%|███████▉  | 127/160 [46:11<12:48, 23.29s/epoch, acc=57.4, loss=0.323]

保存最佳模型，准确率: 57.3971
Epoch 127: Loss=0.3234, Accuracy=57.3971


Training:  80%|████████  | 128/160 [46:36<12:42, 23.84s/epoch, acc=57.5, loss=0.325]

保存最佳模型，准确率: 57.5441
Epoch 128: Loss=0.3251, Accuracy=57.5441


Training:  81%|████████  | 129/160 [46:59<12:16, 23.75s/epoch, acc=57.8, loss=0.305]

保存最佳模型，准确率: 57.8088
Epoch 129: Loss=0.3054, Accuracy=57.8088


Training:  81%|████████▏ | 130/160 [47:23<11:55, 23.84s/epoch, acc=57.9, loss=0.301]

保存最佳模型，准确率: 57.8676
Epoch 130: Loss=0.3014, Accuracy=57.8676


Training:  82%|████████▏ | 131/160 [47:46<11:21, 23.49s/epoch, acc=57.7, loss=0.303]

Epoch 131: Loss=0.3025, Accuracy=57.6912


Training:  82%|████████▎ | 132/160 [48:09<10:56, 23.45s/epoch, acc=57.9, loss=0.297]

Epoch 132: Loss=0.2966, Accuracy=57.8676


Training:  83%|████████▎ | 133/160 [48:31<10:17, 22.87s/epoch, acc=58, loss=0.286]  

保存最佳模型，准确率: 57.9853
Epoch 133: Loss=0.2857, Accuracy=57.9853


Training:  84%|████████▍ | 134/160 [48:52<09:42, 22.42s/epoch, acc=57.8, loss=0.296]

Epoch 134: Loss=0.2960, Accuracy=57.7500


Training:  84%|████████▍ | 135/160 [49:14<09:12, 22.08s/epoch, acc=57.6, loss=0.308]

Epoch 135: Loss=0.3082, Accuracy=57.5735


Training:  85%|████████▌ | 136/160 [49:36<08:53, 22.21s/epoch, acc=58.1, loss=0.281]

保存最佳模型，准确率: 58.1324
Epoch 136: Loss=0.2808, Accuracy=58.1324


Training:  86%|████████▌ | 137/160 [49:59<08:37, 22.49s/epoch, acc=58.2, loss=0.274]

保存最佳模型，准确率: 58.2353
Epoch 137: Loss=0.2744, Accuracy=58.2353


Training:  86%|████████▋ | 138/160 [50:22<08:19, 22.70s/epoch, acc=58.3, loss=0.282]

保存最佳模型，准确率: 58.2794
Epoch 138: Loss=0.2820, Accuracy=58.2794


Training:  87%|████████▋ | 139/160 [50:45<07:54, 22.58s/epoch, acc=58.5, loss=0.27] 

保存最佳模型，准确率: 58.5147
Epoch 139: Loss=0.2698, Accuracy=58.5147


Training:  88%|████████▊ | 140/160 [51:08<07:33, 22.67s/epoch, acc=58.5, loss=0.271]

Epoch 140: Loss=0.2706, Accuracy=58.5147


Training:  88%|████████▊ | 141/160 [51:30<07:06, 22.47s/epoch, acc=58.4, loss=0.272]

Epoch 141: Loss=0.2721, Accuracy=58.3676


Training:  89%|████████▉ | 142/160 [51:53<06:49, 22.78s/epoch, acc=59.1, loss=0.252]

保存最佳模型，准确率: 59.1176
Epoch 142: Loss=0.2515, Accuracy=59.1176


Training:  89%|████████▉ | 143/160 [52:15<06:20, 22.39s/epoch, acc=58.6, loss=0.263]

Epoch 143: Loss=0.2626, Accuracy=58.6471


Training:  90%|█████████ | 144/160 [52:37<05:58, 22.42s/epoch, acc=58.7, loss=0.244]

Epoch 144: Loss=0.2438, Accuracy=58.7206


Training:  91%|█████████ | 145/160 [53:00<05:36, 22.44s/epoch, acc=59, loss=0.252]  

Epoch 145: Loss=0.2519, Accuracy=58.9853


Training:  91%|█████████▏| 146/160 [53:22<05:14, 22.45s/epoch, acc=59.1, loss=0.235]

保存最佳模型，准确率: 59.1324
Epoch 146: Loss=0.2355, Accuracy=59.1324


Training:  92%|█████████▏| 147/160 [53:45<04:53, 22.59s/epoch, acc=59, loss=0.24]   

Epoch 147: Loss=0.2399, Accuracy=58.9853


Training:  92%|█████████▎| 148/160 [54:07<04:30, 22.56s/epoch, acc=59.2, loss=0.247]

保存最佳模型，准确率: 59.1765
Epoch 148: Loss=0.2470, Accuracy=59.1765


Training:  93%|█████████▎| 149/160 [54:32<04:13, 23.05s/epoch, acc=59.3, loss=0.237]

保存最佳模型，准确率: 59.2941
Epoch 149: Loss=0.2367, Accuracy=59.2941


Training:  94%|█████████▍| 150/160 [54:53<03:46, 22.67s/epoch, acc=59.2, loss=0.235]

Epoch 150: Loss=0.2352, Accuracy=59.2353


Training:  94%|█████████▍| 151/160 [55:16<03:24, 22.76s/epoch, acc=59.3, loss=0.228]

Epoch 151: Loss=0.2279, Accuracy=59.2647


Training:  95%|█████████▌| 152/160 [55:41<03:05, 23.24s/epoch, acc=59.5, loss=0.222]

保存最佳模型，准确率: 59.5294
Epoch 152: Loss=0.2217, Accuracy=59.5294


Training:  96%|█████████▌| 153/160 [56:04<02:43, 23.30s/epoch, acc=59.8, loss=0.208]

保存最佳模型，准确率: 59.8382
Epoch 153: Loss=0.2082, Accuracy=59.8382


Training:  96%|█████████▋| 154/160 [56:28<02:21, 23.54s/epoch, acc=59.6, loss=0.214]

Epoch 154: Loss=0.2139, Accuracy=59.6176


Training:  97%|█████████▋| 155/160 [56:52<01:57, 23.56s/epoch, acc=59.6, loss=0.209]

Epoch 155: Loss=0.2092, Accuracy=59.5735


Training:  98%|█████████▊| 156/160 [57:15<01:33, 23.41s/epoch, acc=60, loss=0.202]  

保存最佳模型，准确率: 59.9559
Epoch 156: Loss=0.2021, Accuracy=59.9559


Training:  98%|█████████▊| 157/160 [57:39<01:11, 23.67s/epoch, acc=59.5, loss=0.224]

Epoch 157: Loss=0.2244, Accuracy=59.5147


Training:  99%|█████████▉| 158/160 [58:01<00:46, 23.17s/epoch, acc=59.8, loss=0.206]

Epoch 158: Loss=0.2056, Accuracy=59.7500


Training:  99%|█████████▉| 159/160 [58:23<00:22, 22.86s/epoch, acc=60.2, loss=0.186]

保存最佳模型，准确率: 60.2206
Epoch 159: Loss=0.1857, Accuracy=60.2206


Training: 100%|██████████| 160/160 [58:46<00:00, 22.04s/epoch, acc=60.3, loss=0.189]

保存最佳模型，准确率: 60.3235
Epoch 160: Loss=0.1895, Accuracy=60.3235
训练完成，最终模型已保存
